# Definition de mon image pour mon projet
# Utilisation d'une image officielle et legere de Python
FROM python:3.12-slim

#definition du repertoire de travail dans le container
WORKDIR /app

# copie du fichier de dependances dans le container
COPY requirements.txt .

#Installe les dependances necessaires sanns mise en cache
RUN pip install --no-cache-dir  --upgrade -r requirements.txt

# copie de tout le code de mon projet (fichiers sources et ressources) dans le container
COPY . .

# Commande pour lancer l'application lorsque le container demarre
CMD ["uvicorn","main:app", "--host", "0.0.0.0", "--port", "80"]